### PR TITLE
add caption component

### PR DESCRIPTION
**Pull request by ludwig-pro**
## Checklist before requesting a review
- [x] Working on iOS
- [x] Working on Android
- [ ] Integration tests added
- [x] Visual regressions screenshots are up to date
- [ ] Design validated

### CODE REVIEW

**Review by hcourthias — APPROVED** [review]

**Comment by kimak** [comment]
@ludwig-pro are we sure we need this primitive? 
See my comment in Figma
https://www.figma.com/file/tOJLNigXQXJqCSKgJFPZn5?node-id=4269:11062#433585310

Having too much coupling between components could be risky to introduce regressions. Sometimes it's better to have a bit of duplication instead of too much coupling. WDYT?

**Comment by ianrobertlambert** [comment]
Can we please sync on this if needed so design and code are aligned?

**Comment by kimak** [comment]
Synced with @ianrobertlambert:
- We will remove PrimitiveCaption and PrimitiveLabel
- Rename PrimitiveSkeleton to Skeleton
- Rename PrimitiveSectionTitle to NavigationSectionTitle

Ian will come back to us about PrimitiveOverlay if we rename it NavigationOverlay, just Overlay, or delete it.

**Comment by ianrobertlambert** [comment]
**A quick update on the documentation inside Figma**
- [X] Removed `PrimitiveCaption` and `PrimitiveLabel`. Now built into `Inputs`.
- [X] Renamed `PrimitiveSkeleton` to `Skeleton`
- [X] Renamed `PrimitiveSectionTitle` to `NavigationSectionTitle`

Can we keep the `Overlay` as a dedicated Primitive component for now, since it will be reused not only on `BottomSheet`, `Dialog`, and `DialogFeedback` but also on any future components that require a background overlay? Do you have an alternative suggestion on how to name this @kimak @ludwig-pro @judastheo @hcourthias ?

**Pull request closed without merging**
