### PR TITLE
add appearance to CardCarousel (waiting for @ian to sync on appearance)

### PR DESCRIPTION
**Pull request by hcourthias**
add appearance to cardcarousel

### CODE REVIEW

**Review by judastheo — APPROVED** [review]

**Comment by judastheo** [comment]
@ianrobertlambert Have you sync with Hugo on this PR? Even if not, it is good for you what is proposed?

**Comment by ianrobertlambert** [comment]
Is it possible to see the screenshots in the issue? 🙏 If not, I will look on Expo.

**Comment by judastheo** [comment]
> Is it possible to see the screenshots in the issue? 🙏 If not, I will look on Expo.

The new examples are at the bottom the scroll so the screenshots haven't changed unfortunately^^

**Comment by judastheo** [comment]
@hcourthias @ankisami to close no?

**Pull request closed without merging**
