### PR TITLE
Add streamlined ListItem component

### PR DESCRIPTION
**Pull request by judastheo**
## Checklist before requesting a review
- [x] Working on iOS
- [x] Working on Android
- [x] Integration tests added
- [x] Visual regressions screenshots are up to date
- [ ] Design validated

### CODE REVIEW

**Comment by judastheo** [comment]
@ianrobertlambert @kimak I changed the icon size from 20 to 24 as it is the Designs. The confusion came from the Area icon that had an inner size of 20 but the Icon component that contains it has always been 24. Therefore the screenshots are changed for all the ones using this size of Icon.

Regarding the ListItem, I know the ButtonIcon on the right does not match the Design. It will when we'll handle the latest ButtonIcon designs.

Last for @kimak , I had a typing issue with react-native-ama and opened a discussion on their Github (you'll see the link in a comment on list-item.tsx) so I used the react-native Pressable for now.

**Review by hcourthias — APPROVED** [review]

**Comment by ianrobertlambert** [comment]
Thanks @judastheo ! :)

### Feedback
_No immediate feedback._

### Known Issues
- `ButtonIcon` is outdated and still needs to be updated.

### Questions
- Will the list items have a border radius when displayed in a group, even though they don't currently have one as individual items?
- I find it challenging to validate the `Divider` prop. To confirm, it's only present in the last list item for both iOS and Android? Is this display consistent across all list items? If so, that's great. Thank you.
- Can you confirm if the `Icon`, `Header`, `Description` and `Chevron` are boolean props?

**Comment by judastheo** [comment]
Thanks @ianrobertlambert (I don't find a way to answer right below your comment^^)

- Yes they will!
- Yes, only the last has a divider. What do you mean by consistent?
- `Header` and `Description` are optional. The `Chevron` is displayed only if there is an action on press. For the `Icon`, there is no design without, could you add one to make I have the right spacings in this scenario? I will add more examples

**Comment by ianrobertlambert** [comment]
> - Yes they will!

Ok, great!

> - Yes, only the last has a divider. What do you mean by consistent?

What I meant was that I couldn't see a separator on any of the list items except for the last one. If that display is consistent across all types of list items, then great! :)

> - Header and Description are optional. The Chevron is displayed only if there is an action on press. For the Icon, there is no design without, could you add one to make I have the right spacings in this scenario? I will add more examples

Super clear. The component has a Boolean property that enables the icon and it's enabled by default.

image


Is it necessary to explicitly include an example in the documentation? Removing the icon doesn't affect the spacing or padding. See below:

image

**Comment by judastheo** [comment]
@ianrobertlambert Got it!

When there is no icon, does it impact the divider, should it start at the start of the text or always at the same place, wether or not there's an icon?

**Comment by ianrobertlambert** [comment]
@judastheo Yes, it does impact the divider. The divider should always start at the beginning of the text please. 🙏

image

**Pull request merged**
