### PR TITLE
adjust Markdown component

### PR DESCRIPTION
**Pull request by hcourthias**
As discussed with @ianrobertlambert
- add border radius on images
- add margin bottom on headers

## Checklist before requesting a review
- [x] Working on iOS
- [x] Working on Android
- [ ] Integration tests added
- [x] Visual regressions screenshots are up to date
- [x] Design validated

### CODE REVIEW

**Comment by hcourthias** [comment]
Here are some examples @ianrobertlambert

**Review by judastheo — APPROVED** [review]
Make sure you wait for @ianrobertlambert validation!

**Comment by ianrobertlambert** [comment]
Thanks for sharing @hcourthias ! When trying to access the Expo link, all I see is this:

image

Does it still need to be updated?

**Comment by hcourthias** [comment]
> Thanks for sharing @hcourthias ! When trying to access the Expo link, all I see is this:
> 
> image
> 
> Does it still need to be updated?

I just tried with different image, but we will only keep the luko logo on the sandbox

**Comment by kimak** [comment]
> 🚀 Expo preview is ready!
> 
> * Project → **sandbox**
> * Platforms → **android**, **ios**
> * Runtime Version → **exposdk:48.0.0**
> * **[More info](https://expo.dev/projects/11eb7a11-ac37-40c7-a649-095da5a7b0b3/updates/c40d25cd-1cb0-40a0-8661-c867d9721b5e)**
> 
> [](https://qr.expo.dev/eas-update?projectId=11eb7a11-ac37-40c7-a649-095da5a7b0b3&groupId=c40d25cd-1cb0-40a0-8661-c867d9721b5e)
> 
> > Learn more about [𝝠 Expo Github Action](https://github.com/expo/expo-github-action/tree/main/preview#example-workflows)

@ianrobertlambert all feedback from this comment https://github.com/GetLuko/streamline/pull/61#issuecomment-1589646300 are testable with this QR code

**Comment by ianrobertlambert** [comment]
Just tested on my devices. All good from my side. Thanks! 🙌

**Comment by judastheo** [comment]
@kimak @hcourthias Let's merge no?

**Pull request merged**
